# Generated by Django 5.2.8 on 2026-02-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resolutionrequest_updated_at'),
    ]

    operations = [
    ]
