# Generated by Django 5.2.8 on 2026-02-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20260213_0307'),
    ]

    operations = [
    ]
