# Generated by Django 5.2.8 on 2026-02-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260213_0333'),
    ]

    operations = [
    ]
